module.exports = [
  {
    text: "Where's Your Ed At",
    author: "Ed Zitron",
    authorWiki: "Ed Zitron",
    tags: ["technology"],
    xmlUrl: "https://www.wheresyoured.at/rss/",
    htmlUrl: "https://www.wheresyoured.at/",
  },
  {
    text: "Ludicity",
    author: "Nikhil Suresh",
    tags: ["technology"],
    xmlUrl: "https://ludic.mataroa.blog/rss/",
    htmlUrl: "https://ludic.mataroa.blog/",
  },
  {
    author: "Simon Willison",
    authorWiki: "Simon Willison",
    tags: ["technology"],
    xmlUrl: "https://simonwillison.net/atom/everything/",
    htmlUrl: "http://simonwillison.net/",
  },
  {
    text: "BAD ASIAN",
    author: "Katy Ho",
    tags: ["Substack"],
    xmlUrl: "https://katyho.substack.com/feed",
    htmlUrl: "https://katyho.substack.com/",
  },
  {
    author: "Dan Wang",
    authorWiki: "Dan Wang (analyst)",
    xmlUrl: "https://danwang.co/?feed=rss",
    htmlUrl: "https://danwang.co/",
  },
  {
    author: "Siobhan Brier Aguilar",
    xmlUrl: "https://siobhanbrier.com/rss",
    htmlUrl: "https://siobhanbrier.com/",
  },
  {
    text: "Grown-Up Gen-Z",
    author: "Janice Journal",
    tags: ["Substack"],
    xmlUrl: "https://janicejournal.substack.com/feed",
    htmlUrl: "https://janicejournal.substack.com/",
  },
  {
    text: "Skepchick",
    author: "Rebecca Watson",
    authorWiki: "Rebecca Watson",
    tags: ["skepticism"],
    xmlUrl: "https://skepchick.org/feed",
    htmlUrl: "https://skepchick.org/",
  },
  {
    text: "The BS Detector",
    author: "Ben Shindel",
    tags: ["Substack"],
    xmlUrl: "https://thebsdetector.substack.com/feed",
    htmlUrl: "https://thebsdetector.substack.com/",
  },
  {
    text: "Slow Boring",
    author: "Matthew Yglesias",
    authorWiki: "Matthew Yglesias",
    tags: ["Substack", "economics"],
    xmlUrl: "https://www.slowboring.com/feed",
    htmlUrl: "https://www.slowboring.com/",
  },
  {
    author: "Karl Whelan",
    xmlUrl: "https://karlwhelan.com/blog/?feed=rss2",
    htmlUrl: "https://karlwhelan.com/blog/",
  },
  {
    text: "Noahpinion",
    author: "Noah Smith",
    tags: ["Substack", "economics"],
    xmlUrl: "https://www.noahpinion.blog/feed",
    htmlUrl: "https://www.noahpinion.blog/",
  },
  {
    text: "M3_Melody",
    author: "Melody Wright",
    tags: ["Substack"],
    xmlUrl: "https://m3melody.substack.com/feed",
    htmlUrl: "https://m3melody.substack.com/",
  },
  {
    text: "Yes, I give a fig... thoughts on markets",
    author: "Michael Green",
    tags: ["Substack", "economics"],
    xmlUrl: "https://www.yesigiveafig.com/feed",
    htmlUrl: "https://www.yesigiveafig.com/",
  },
  {
    text: "The Discourse Lounge",
    author: "Darrell Owens",
    tags: ["Substack"],
    xmlUrl: "https://darrellowens.substack.com/feed",
    htmlUrl: "https://darrellowens.substack.com/",
  },
  {
    text: "EconomPic",
    author: "Jake",
    tags: ["economics"],
    xmlUrl: "https://econompicdata.blogspot.com/feeds/posts/default",
    htmlUrl: "https://econompicdata.blogspot.com/",
  },
  {
    text: "Observations on film art",
    author: "David Bordwell",
    authorWiki: "David Bordwell",
    tags: ["film", "culture"],
    xmlUrl: "https://www.davidbordwell.net/blog/feed",
    htmlUrl: "https://www.davidbordwell.net/blog",
  },
  {
    text: "Midnight Musings",
    author: "Shiyoon Kim",
    authorWiki: "Shiyoon Kim",
    tags: ["Substack", "art", "culture"],
    xmlUrl: "https://shiyoonk.substack.com/feed",
    htmlUrl: "https://shiyoonk.substack.com/",
  },
  {
    text: "McMansion Hell",
    author: "Kate Wagner",
    authorWiki: "McMansion Hell",
    tags: ["culture"],
    xmlUrl: "https://mcmansionhell.com/rss",
    htmlUrl: "https://mcmansionhell.com/",
  },
  {
    text: "the late review",
    author: "Kate Wagner",
    tags: ["Substack", "culture"],
    xmlUrl: "https://www.late-review.com/feed",
    htmlUrl: "https://www.late-review.com/",
  },
  {
    author: "Dayn Broder",
    xmlUrl: "https://www.daynbroder.com/blog-feed.xml",
    htmlUrl: "https://www.daynbroder.com/",
  },
  {
    text: "Kat's Canvas",
    author: "Kat Tsai",
    tags: ["Substack", "art"],
    xmlUrl: "https://chuwenjie.substack.com/feed",
    htmlUrl: "https://chuwenjie.substack.com/",
  },
  {
    text: "The Column",
    author: "Adam Johnson",
    tags: ["Substack"],
    xmlUrl: "https://www.columnblog.com/feed",
    htmlUrl: "https://www.columnblog.com/",
  },
  {
    text: "GenderSci Lab",
    tags: ["LGBT"],
    xmlUrl: "https://www.genderscilab.org/blog?format=rss",
    htmlUrl: "https://www.genderscilab.org/blog/",
  },
];
