module.exports = [
  {
    text: "Assigned Media",
    tags: ["LGBT"],
    xmlUrl: "https://www.assignedmedia.org/breaking-news?format=rss",
    htmlUrl: "https://www.assignedmedia.org/",
  },
  {
    text: "Where's Your Ed At",
    author: "Ed Zitron",
    authorWiki: "Ed Zitron",
    tags: ["technology"],
    xmlUrl: "https://www.wheresyoured.at/rss/",
    htmlUrl: "https://www.wheresyoured.at/",
  },
  {
    text: "User Mag",
    author: "Taylor Lorenz",
    authorWiki: "Taylor Lorenz",
    tags: ["Substack"],
    xmlUrl: "https://www.usermag.co/feed",
    htmlUrl: "https://www.usermag.co/",
  },
  {
    text: "BAD ASIAN",
    author: "Katy Ho",
    tags: ["culture", "Substack"],
    xmlUrl: "https://katyho.substack.com/feed",
    htmlUrl: "https://katyho.substack.com/",
  },
  {
    text: "New Cartographies",
    author: "Nicholas Carr",
    authorWiki: "Nicholas G. Carr",
    tags: ["Substack"],
    xmlUrl: "https://www.newcartographies.com/feed",
    htmlUrl: "https://www.newcartographies.com/",
  },
  {
    text: "Citation Needed",
    author: "Molly White",
    authorWiki: "Molly White (writer)",
    xmlUrl: "https://www.citationneeded.news/rss/",
    htmlUrl: "https://www.citationneeded.news/",
  },
  {
    text: "Strength in Numbers",
    author: "G. Elliott Morris",
    authorWiki: "G. Elliott Morris",
    tags: ["Substack"],
    xmlUrl: "https://www.gelliottmorris.com/feed",
    htmlUrl: "https://www.gelliottmorris.com/",
  },
  {
    text: "Works in Progress",
    tags: ["Substack"],
    xmlUrl: "https://www.worksinprogress.news/feed",
    htmlUrl: "https://www.worksinprogress.news/",
  },
  {
    text: "The BS Detector",
    author: "Ben Shindel",
    tags: ["Substack"],
    xmlUrl: "https://thebsdetector.substack.com/feed",
    htmlUrl: "https://thebsdetector.substack.com/",
  },
  {
    text: "Pearls and Irritations",
    author: "John Menadue",
    authorWiki: "John Menadue",
    xmlUrl: "https://johnmenadue.com/feed",
    htmlUrl: "https://johnmenadue.com",
  },
  {
    text: "Slow Boring",
    author: "Matthew Yglesias",
    authorWiki: "Matthew Yglesias",
    tags: ["economics", "Substack"],
    xmlUrl: "https://www.slowboring.com/feed",
    htmlUrl: "https://www.slowboring.com/",
  },
  {
    text: "Chartbook",
    author: "Adam Tooze",
    authorWiki: "Adam Tooze",
    tags: ["economics", "Substack"],
    xmlUrl: "https://adamtooze.substack.com/feed",
    htmlUrl: "https://adamtooze.substack.com/",
  },
  {
    text: "Noahpinion",
    author: "Noah Smith",
    tags: ["economics", "Substack"],
    xmlUrl: "https://www.noahpinion.blog/feed",
    htmlUrl: "https://www.noahpinion.blog/",
  },
  {
    text: "Doomberg",
    tags: ["energy", "Substack"],
    xmlUrl: "https://newsletter.doomberg.com/feed",
    htmlUrl: "https://newsletter.doomberg.com/",
  },
  {
    text: "Blackbird Spyplane",
    tags: ["culture", "Substack"],
    xmlUrl: "https://www.blackbirdspyplane.com/feed",
    htmlUrl: "https://www.blackbirdspyplane.com/",
  },
  {
    text: "HouseFresh",
    xmlUrl: "https://housefresh.com/feed/",
    htmlUrl: "https://housefresh.com/",
  },
  {
    text: "Volts",
    author: "David Roberts",
    tags: ["energy", "Substack"],
    xmlUrl: "https://www.volts.wtf/feed",
    htmlUrl: "https://www.volts.wtf/",
  },
  {
    text: "The Up and Up",
    author: "Rachel Janfaza",
    tags: ["Substack"],
    xmlUrl: "https://www.theupandup.us/feed",
    htmlUrl: "https://www.theupandup.us/",
  },
  {
    text: "ImmunoLogic",
    author: "Dr. Andrea Love",
    tags: ["Substack"],
    xmlUrl: "https://news.immunologic.org/feed",
    htmlUrl: "https://news.immunologic.org/",
  },
  {
    text: "Big",
    author: "Matt Stoller",
    authorWiki: "Matt Stoller",
    tags: ["Substack"],
    xmlUrl: "https://www.thebignewsletter.com/feed",
    htmlUrl: "https://www.thebignewsletter.com/",
  },
  {
    text: "Big Tech on Trial",
    author: "Matt Stoller",
    authorWiki: "Matt Stoller",
    tags: ["Substack"],
    xmlUrl: "https://www.bigtechontrial.com/feed",
    htmlUrl: "https://www.bigtechontrial.com/",
  },
];